### ISSUE TITLE
Unable to erase flash

### ISSUE THREAD

**Issue by joaopbnogueira** [horvathgergo/esp8266-for-fornuftig#4]
Hi, this might be a noob question but I can't seem to be able to erase the flash using `esptool.py`

- I'm using a USB-to-TTL adapter (with PL2303) and 5VDC (https://mauser.pt/catalog/product_info.php?products_id=096-7521)
- When pluggin in the VDC, I get a short blink of the esp led
- When running `python -m serial.tools.miniterm "$PORT"` and hitting the RST button get random chars on the console (using the recommended baudrate of 74880)
- When running `esptool.py --port "$PORT" erase_flash` I get `Serial data stream stopped: Possible serial noise or corruption.`

Any tips? Thank you!

**Comment by joaopbnogueira** [comment]
I checked the GND and VND pins on the esp-12f and they were a bit low with the 5V supply (around 3.0V), using the device's 24V raised it to the target 3.3V, but still get the same corruption error. Any hint to debug? Also tested with an FT232R and 9600 baud rate...

**Comment by horvathgergo** [comment]
Have you tried flashing ESPHome? It worked for others, and if it works for you too, that's a hint to exclude a possible hardware error

**Comment by joaopbnogueira** [comment]
hey @horvathgergo I was able to sort this out.

For reference and maybe to help others these were the steps:
- Connect an external power supply (not using the TTL/serial adapter for power) and verify 3.3V on the ESP-12F
- Make sure that GND for the TTL adapter is shared with GND from the power supply (short)
- Read esp-12f datasheet and notice GPIO 15 should be down for flashing
- Hold boot button, hold reset, release reset, release boot.
- Verify that GPIO15 is down 0V to GND
- Flash using https://web.esphome.io/ straight from the browser.
- Success!
